package com.uplb.punla.ui.theme

import com.uplb.punla.data.ThemePreset

/** Display metadata for Settings → Appearance. */
data class ThemeDescriptor(
    val preset: ThemePreset,
    val name: String,
    val modeLabel: String,
    val category: String,
    val description: String,
    val palette: PunlaPalette,
    val designedForDark: Boolean,
)

val PunlaThemeCatalog: List<ThemeDescriptor> = listOf(
    ThemeDescriptor(
        ThemePreset.FIELD_NOTEBOOK,
        "Field Notebook",
        "Light + Dark",
        "Punla Classic",
        "The original warm paper-and-leaf Punla look.",
        Palettes.FieldNotebook,
        designedForDark = false,
    ),
    ThemeDescriptor(
        ThemePreset.AURORA_BOREALIS,
        "Aurora Borealis",
        "Dark",
        "Nature",
        "Deep navy with teal, emerald, and cool blue light.",
        Palettes.AuroraBorealis,
        designedForDark = true,
    ),
    ThemeDescriptor(
        ThemePreset.SUNSET_SKY,
        "Sunset Sky",
        "Dark",
        "Nature",
        "Warm coral, pink, and violet for evening planning.",
        Palettes.SunsetSky,
        designedForDark = true,
    ),
    ThemeDescriptor(
        ThemePreset.OCEAN_DEPTHS,
        "Ocean Depths",
        "Dark",
        "Nature",
        "Calming deep blues with cyan and aqua accents.",
        Palettes.OceanDepths,
        designedForDark = true,
    ),
    ThemeDescriptor(
        ThemePreset.FOREST_MIST,
        "Forest Mist",
        "Dark",
        "Nature",
        "Muted moss, foggy greens, and grounded earth tones.",
        Palettes.ForestMist,
        designedForDark = true,
    ),
    ThemeDescriptor(
        ThemePreset.LAVENDER_NIGHT,
        "Lavender Night",
        "Dark",
        "Nature",
        "Soft indigo and lavender for late-night study.",
        Palettes.LavenderNight,
        designedForDark = true,
    ),
    ThemeDescriptor(
        ThemePreset.GOLDEN_DAWN,
        "Golden Dawn",
        "Light",
        "Nature",
        "Cream, peach, and gold for bright morning planning.",
        Palettes.GoldenDawn,
        designedForDark = false,
    ),
    ThemeDescriptor(
        ThemePreset.COFFEE_SHOP,
        "Coffee Shop",
        "Dark",
        "Cozy",
        "Mocha surfaces and caramel accents for relaxed study.",
        Palettes.CoffeeShop,
        designedForDark = true,
    ),
    ThemeDescriptor(
        ThemePreset.LOFI_NIGHT,
        "Lo-fi Night",
        "Dark",
        "Cozy",
        "Moody navy, pink, violet, and soft neon blue.",
        Palettes.LofiNight,
        designedForDark = true,
    ),
    ThemeDescriptor(
        ThemePreset.PAPER_INK,
        "Paper & Ink",
        "Light",
        "Cozy · Minimal",
        "Off-white paper, dark ink, and restrained accents.",
        Palettes.PaperInk,
        designedForDark = false,
    ),
    ThemeDescriptor(
        ThemePreset.LIBRARY_MODE,
        "Library Mode",
        "Dark",
        "Cozy",
        "Dark wood, parchment, brass, and academic green.",
        Palettes.LibraryMode,
        designedForDark = true,
    ),
    ThemeDescriptor(
        ThemePreset.CYBER_NEON,
        "Cyber Neon",
        "Dark",
        "Modern",
        "Near-black surfaces with cyan, magenta, and lime.",
        Palettes.CyberNeon,
        designedForDark = true,
    ),
    ThemeDescriptor(
        ThemePreset.PASTEL_BLOOM,
        "Pastel Bloom",
        "Light",
        "Modern",
        "Friendly pink, mint, and blue pastel tones.",
        Palettes.PastelBloom,
        designedForDark = false,
    ),
    ThemeDescriptor(
        ThemePreset.FROST_GLASS,
        "Frost Glass",
        "Light",
        "Modern · Minimal",
        "Cool pale blues with crisp frosted surfaces.",
        Palettes.FrostGlass,
        designedForDark = false,
    ),
    ThemeDescriptor(
        ThemePreset.GALAXY,
        "Galaxy",
        "Dark",
        "Modern",
        "Deep-space navy with violet, blue, and pink glow.",
        Palettes.Galaxy,
        designedForDark = true,
    ),
)
