package com.uplb.punla.data

import com.uplb.punla.data.entity.Quiz
import com.uplb.punla.data.entity.QuizQuestion
import com.uplb.punla.data.entity.QuizQuestionTypes
import org.json.JSONArray
import org.json.JSONException
import org.json.JSONObject

/** Type-safe JSON interchange for quizzes generated by ChatGPT or Punla. */
data class QuizJsonQuestion(
    val type: String,
    val prompt: String,
    val options: List<String>,
    val correctAnswer: String,
    val explanation: String? = null,
    val tags: String = ""
)

data class QuizJsonPayload(
    val contentId: String,
    val title: String,
    val courseCode: String? = null,
    val description: String? = null,
    val passingScore: Int = 70,
    val shuffleQuestions: Boolean = true,
    val shuffleChoices: Boolean = true,
    val questions: List<QuizJsonQuestion>,
    val warnings: List<String> = emptyList()
)

object QuizJsonImport {
    const val FILE_ID = PunlaJsonFileIds.QUIZ
    const val VERSION = 1
    const val MAX_FILE_CHARS = 4_000_000
    const val MAX_QUESTIONS = 1_000

    fun parse(raw: String): QuizJsonPayload {
        require(raw.length <= MAX_FILE_CHARS) { "This JSON file is too large. Keep quiz imports under about 4 MB." }
        val text = raw.trim().removePrefix("\uFEFF").trim()
        require(text.isNotEmpty()) { "The selected file is empty." }
        val root = try { JSONObject(text) } catch (e: JSONException) {
            throw IllegalArgumentException("Punla couldn't read this quiz JSON. Check that it is valid JSON.", e)
        }
        val actualFileId = root.optString("punlaFileId").trim()
        require(actualFileId.isNotEmpty()) {
            "This JSON has no Punla file ID. For safety, Quizzes accepts only JSON generated specifically for Punla Quiz."
        }
        if (actualFileId != FILE_ID) throw PunlaJsonFileIds.wrongImporter(actualFileId, FILE_ID)
        val version = root.optInt("schemaVersion", -1)
        require(version in 1..VERSION) {
            if (version > VERSION) "This quiz JSON uses schema v$version, but this Punla build supports up to v$VERSION."
            else "This quiz JSON is missing a supported schemaVersion."
        }
        val contentId = PunlaJsonFileIds.requireUuid(root.optString("contentId").trim())
        val quiz = root.optJSONObject("quiz") ?: throw IllegalArgumentException("This quiz JSON is missing its 'quiz' object.")
        val title = firstText(quiz, "title", "name") ?: throw IllegalArgumentException("The quiz has no title.")
        val courseCode = firstText(quiz, "courseCode", "course", "subject")
        val description = firstText(quiz, "description", "notes")
        val passingScore = quiz.optInt("passingScore", 70).coerceIn(1, 100)
        val shuffleQuestions = quiz.optBoolean("shuffleQuestions", true)
        val shuffleChoices = quiz.optBoolean("shuffleChoices", true)
        val array = root.optJSONArray("questions") ?: throw IllegalArgumentException("This quiz JSON has no 'questions' array.")
        val warnings = mutableListOf<String>()
        val questions = parseQuestions(array, warnings)
        require(questions.isNotEmpty()) { "No valid quiz questions were found in this JSON file." }
        return QuizJsonPayload(
            contentId = contentId,
            title = title.take(120),
            courseCode = courseCode?.take(60),
            description = description?.take(1_000),
            passingScore = passingScore,
            shuffleQuestions = shuffleQuestions,
            shuffleChoices = shuffleChoices,
            questions = questions,
            warnings = warnings
        )
    }

    private fun parseQuestions(array: JSONArray, warnings: MutableList<String>): List<QuizJsonQuestion> {
        val limit = minOf(array.length(), MAX_QUESTIONS)
        if (array.length() > MAX_QUESTIONS) warnings += "Only the first $MAX_QUESTIONS questions were imported."
        val out = ArrayList<QuizJsonQuestion>(limit)
        var skipped = 0
        for (index in 0 until limit) {
            val obj = array.optJSONObject(index)
            if (obj == null) { skipped++; continue }
            val prompt = firstText(obj, "question", "prompt", "stem")
            if (prompt.isNullOrBlank()) { skipped++; continue }
            val rawType = firstText(obj, "type")?.lowercase().orEmpty()
            val type = when (rawType) {
                "multiple_choice", "multiple-choice", "mcq", "choice" -> QuizQuestionTypes.MULTIPLE_CHOICE
                "true_false", "true-false", "boolean", "tf" -> QuizQuestionTypes.TRUE_FALSE
                "identification", "short_answer", "short-answer", "typed", "text" -> QuizQuestionTypes.IDENTIFICATION
                else -> {
                    if (obj.optJSONArray("choices") != null || obj.optJSONArray("options") != null) QuizQuestionTypes.MULTIPLE_CHOICE
                    else QuizQuestionTypes.IDENTIFICATION
                }
            }
            val options = when (type) {
                QuizQuestionTypes.TRUE_FALSE -> listOf("True", "False")
                QuizQuestionTypes.MULTIPLE_CHOICE -> parseOptions(obj.optJSONArray("choices") ?: obj.optJSONArray("options"))
                else -> emptyList()
            }
            if (type == QuizQuestionTypes.MULTIPLE_CHOICE && options.size < 2) { skipped++; continue }
            val answer = parseAnswer(obj, type, options)
            if (answer.isNullOrBlank()) { skipped++; continue }
            if (type == QuizQuestionTypes.MULTIPLE_CHOICE && options.none { QuizQuestion.normalizeAnswer(it) == QuizQuestion.normalizeAnswer(answer) }) {
                warnings += "Question ${index + 1} had an answer that did not match any choice and was skipped."
                skipped++
                continue
            }
            if (type == QuizQuestionTypes.TRUE_FALSE && answer.lowercase() !in setOf("true", "false")) {
                skipped++
                continue
            }
            out += QuizJsonQuestion(
                type = type,
                prompt = prompt.take(20_000),
                options = options.take(8),
                correctAnswer = when (type) {
                    QuizQuestionTypes.TRUE_FALSE -> if (answer.equals("true", true)) "True" else "False"
                    else -> answer.take(10_000)
                },
                explanation = firstText(obj, "explanation", "feedback", "rationale")?.take(20_000),
                tags = parseTags(obj.opt("tags")).take(1_000)
            )
        }
        if (skipped > 0) warnings += "$skipped invalid question${if (skipped == 1) " was" else "s were"} skipped."
        return out
    }

    private fun parseOptions(array: JSONArray?): List<String> {
        if (array == null) return emptyList()
        val out = mutableListOf<String>()
        for (i in 0 until minOf(array.length(), 8)) {
            array.optString(i).trim().takeIf { it.isNotEmpty() }?.let { if (it !in out) out += it }
        }
        return out
    }

    private fun parseAnswer(obj: JSONObject, type: String, options: List<String>): String? {
        val raw = when {
            obj.has("correctAnswer") -> obj.opt("correctAnswer")
            obj.has("answer") -> obj.opt("answer")
            obj.has("correct") -> obj.opt("correct")
            else -> null
        } ?: return null
        return when (raw) {
            is Number -> {
                if (type != QuizQuestionTypes.MULTIPLE_CHOICE) raw.toString()
                else options.getOrNull(raw.toInt())
            }
            is Boolean -> if (raw) "True" else "False"
            else -> {
                val text = raw.toString().trim()
                if (type == QuizQuestionTypes.MULTIPLE_CHOICE && text.length == 1 && text[0].uppercaseChar() in 'A'..'H') {
                    options.getOrNull(text[0].uppercaseChar() - 'A') ?: text
                } else text
            }
        }
    }

    private fun parseTags(value: Any?): String = when (value) {
        is JSONArray -> buildList {
            for (i in 0 until value.length()) value.optString(i).trim().takeIf { it.isNotEmpty() }?.let(::add)
        }.distinct().joinToString(", ")
        is String -> value.split(',').map { it.trim() }.filter { it.isNotEmpty() }.distinct().joinToString(", ")
        else -> ""
    }

    private fun firstText(obj: JSONObject?, vararg keys: String): String? {
        if (obj == null) return null
        for (key in keys) {
            if (!obj.has(key) || obj.isNull(key)) continue
            val value = obj.optString(key).trim()
            if (value.isNotEmpty()) return value
        }
        return null
    }
}

object QuizJsonExport {
    fun build(quiz: Quiz, questions: List<QuizQuestion>): String = JSONObject().apply {
        put("punlaFileId", QuizJsonImport.FILE_ID)
        put("schemaVersion", QuizJsonImport.VERSION)
        put("contentId", quiz.id)
        put("quiz", JSONObject().apply {
            put("title", quiz.title)
            quiz.courseCode?.let { put("courseCode", it) }
            quiz.description?.let { put("description", it) }
            put("passingScore", quiz.passingScore)
            put("shuffleQuestions", quiz.shuffleQuestions)
            put("shuffleChoices", quiz.shuffleChoices)
        })
        put("questions", JSONArray().apply {
            questions.forEach { question ->
                put(JSONObject().apply {
                    put("type", when (question.type) {
                        QuizQuestionTypes.TRUE_FALSE -> "true_false"
                        QuizQuestionTypes.IDENTIFICATION -> "identification"
                        else -> "multiple_choice"
                    })
                    put("question", question.prompt)
                    if (question.type == QuizQuestionTypes.MULTIPLE_CHOICE) put("choices", JSONArray(question.options()))
                    put("correctAnswer", question.correctAnswer)
                    question.explanation?.let { put("explanation", it) }
                    if (question.tags.isNotBlank()) put("tags", JSONArray(question.tagList()))
                })
            }
        })
    }.toString(2)
}
