package com.uplb.punla.data

import com.uplb.punla.data.entity.FlashcardTypes
import com.uplb.punla.data.entity.QuizQuestion
import com.uplb.punla.data.entity.QuizQuestionTypes
import org.json.JSONArray
import org.json.JSONException
import org.json.JSONObject

/**
 * Safe interchange for complete study packs generated by ChatGPT/Punla.
 * Review history, mastery, scores and attempt data are intentionally absent.
 */
data class StudyJsonTopic(
    val key: String,
    val name: String,
    val parentKey: String? = null,
    val examDate: String? = null,
    val priority: Int = 3,
    val sortOrder: Int = 0
)

data class StudyJsonNote(val title: String, val body: String, val topicKey: String? = null, val tags: String = "")
data class StudyJsonFormula(val title: String, val expression: String, val topicKey: String? = null, val variables: String? = null, val units: String? = null, val workedExample: String? = null)
data class StudyJsonCard(
    val front: String,
    val back: String,
    val hint: String? = null,
    val tags: String = "",
    val starred: Boolean = false,
    val reverseEnabled: Boolean = false,
    val cardType: String = FlashcardTypes.BASIC,
    val imageUri: String? = null,
    val occlusionJson: String = "[]"
)
data class StudyJsonDeck(val name: String, val description: String? = null, val topicKey: String? = null, val cards: List<StudyJsonCard>)
data class StudyJsonQuestion(
    val type: String,
    val prompt: String,
    val options: List<String>,
    val correctAnswer: String,
    val explanation: String? = null,
    val tags: String = "",
    val metadataJson: String = "{}",
    val imageUri: String? = null
)
data class StudyJsonQuiz(val title: String, val description: String? = null, val topicKey: String? = null, val passingScore: Int = 70, val questions: List<StudyJsonQuestion>)

data class StudyJsonBundle(
    val fileId: String,
    val contentId: String,
    val title: String,
    val courseCode: String? = null,
    val description: String? = null,
    val topics: List<StudyJsonTopic> = emptyList(),
    val notes: List<StudyJsonNote> = emptyList(),
    val formulas: List<StudyJsonFormula> = emptyList(),
    val decks: List<StudyJsonDeck> = emptyList(),
    val quizzes: List<StudyJsonQuiz> = emptyList(),
    val warnings: List<String> = emptyList()
) {
    val itemCount: Int get() = topics.size + notes.size + formulas.size + decks.sumOf { it.cards.size } + quizzes.sumOf { it.questions.size }
}

object StudyJsonImport {
    const val BUNDLE_FILE_ID = PunlaJsonFileIds.STUDY_BUNDLE
    const val NOTES_FILE_ID = PunlaJsonFileIds.STUDY_NOTES
    const val VERSION = 1
    const val MAX_FILE_CHARS = 6_000_000
    const val MAX_TOPICS = 300
    const val MAX_NOTES = 500
    const val MAX_FORMULAS = 500
    const val MAX_DECKS = 50
    const val MAX_CARDS = 5_000
    const val MAX_QUIZZES = 50
    const val MAX_QUESTIONS = 2_000

    fun parse(raw: String): StudyJsonBundle {
        require(raw.length <= MAX_FILE_CHARS) { "This study JSON is too large. Keep imports under about 6 MB." }
        val text = raw.trim().removePrefix("\uFEFF").trim()
        require(text.isNotEmpty()) { "The selected file is empty." }
        val root = try { JSONObject(text) } catch (e: JSONException) {
            throw IllegalArgumentException("Punla couldn't read this study JSON. Check that it is valid JSON.", e)
        }
        val fileId = root.optString("punlaFileId").trim()
        require(fileId.isNotEmpty()) { "This JSON has no Punla file ID. Ask ChatGPT to regenerate it using the Punla Study JSON format." }
        if (fileId !in setOf(BUNDLE_FILE_ID, NOTES_FILE_ID)) throw PunlaJsonFileIds.wrongImporter(fileId, BUNDLE_FILE_ID)
        val version = root.optInt("schemaVersion", -1)
        require(version in 1..VERSION) { "This study JSON uses unsupported schemaVersion $version. This Punla build supports v$VERSION." }
        val contentId = PunlaJsonFileIds.requireUuid(root.optString("contentId").trim())
        val bundle = root.optJSONObject("bundle") ?: root.optJSONObject("study") ?: JSONObject()
        val title = firstText(bundle, "title", "name") ?: firstText(root, "title", "name") ?: "Imported Study Pack"
        val course = firstText(bundle, "courseCode", "course", "subject") ?: firstText(root, "courseCode", "course", "subject")
        val description = firstText(bundle, "description", "notes")
        val warnings = mutableListOf<String>()
        // Accept both documented layouts: material arrays may live at the
        // top level or inside the "bundle"/"study" object that carries title
        // and course metadata.
        fun array(vararg names: String): JSONArray? {
            for (name in names) {
                root.optJSONArray(name)?.let { return it }
                bundle.optJSONArray(name)?.let { return it }
            }
            return null
        }
        val topics = parseTopics(array("topics"), warnings)
        val notes = parseNotes(array("notes", "reviewers"), warnings)
        val formulas = parseFormulas(array("formulas", "formulaReferences"), warnings)
        val decks = if (fileId == NOTES_FILE_ID) emptyList()
        else parseDecks(array("flashcardDecks", "decks"), warnings)
        val quizzes = if (fileId == NOTES_FILE_ID) emptyList()
        else parseQuizzes(array("quizzes"), warnings)
        require(topics.isNotEmpty() || notes.isNotEmpty() || formulas.isNotEmpty() || decks.isNotEmpty() || quizzes.isNotEmpty()) {
            "No supported study material was found in this JSON file."
        }
        return StudyJsonBundle(fileId, contentId, title.take(160), course?.take(60), description?.take(2_000), topics, notes, formulas, decks, quizzes, warnings)
    }

    private fun parseTopics(a: JSONArray?, warnings: MutableList<String>): List<StudyJsonTopic> {
        if (a == null) return emptyList()
        val out = mutableListOf<StudyJsonTopic>()
        val usedKeys = mutableSetOf<String>()
        var skipped = 0
        var duplicateKeys = 0
        for (i in 0 until minOf(a.length(), MAX_TOPICS)) {
            val o = a.optJSONObject(i)
            if (o == null) {
                skipped++
                continue
            }
            val name = firstText(o, "name", "title")
            if (name == null) {
                skipped++
                continue
            }
            val rawKey = (firstText(o, "key", "id", "slug") ?: "topic-$i").take(100)
            val normalizedKey = rawKey.lowercase()
            if (!usedKeys.add(normalizedKey)) {
                duplicateKeys++
                continue
            }
            val exam = firstText(o, "examDate", "exam")
            val validExam = exam?.takeIf { runCatching { java.time.LocalDate.parse(it) }.isSuccess }
            if (exam != null && validExam == null) {
                warnings += "Topic '${name.take(40)}' had an invalid examDate and it was ignored."
            }
            out += StudyJsonTopic(
                key = rawKey,
                name = name.take(200),
                parentKey = firstText(o, "parentKey", "parent")?.take(100),
                examDate = validExam,
                priority = o.optInt("priority", 3).coerceIn(1, 5),
                sortOrder = o.optInt("sortOrder", o.optInt("order", i)).coerceAtLeast(0)
            )
        }
        if (a.length() > MAX_TOPICS) warnings += "Only the first $MAX_TOPICS topics were imported."
        if (skipped > 0) warnings += "$skipped invalid topic${if (skipped == 1) " was" else "s were"} skipped."
        if (duplicateKeys > 0) warnings += "$duplicateKeys topic${if (duplicateKeys == 1) " had" else "s had"} a duplicate key and ${if (duplicateKeys == 1) "was" else "were"} skipped."
        val keys = out.map { it.key.lowercase() }.toSet()
        out.filter { it.parentKey != null && it.parentKey.lowercase() !in keys }.forEach {
            warnings += "Topic '${it.name.take(40)}' references an unknown parent '${it.parentKey}'; it will be imported at the top level."
        }
        return out
    }

    private fun parseNotes(a: JSONArray?, warnings: MutableList<String>): List<StudyJsonNote> {
        if (a == null) return emptyList()
        val out = mutableListOf<StudyJsonNote>()
        var skipped = 0
        for (i in 0 until minOf(a.length(), MAX_NOTES)) {
            val o = a.optJSONObject(i)
            val title = o?.let { firstText(it, "title", "name") }
            val body = o?.let { firstText(it, "body", "content", "text") }
            if (o == null || title == null || body == null) {
                skipped++
                continue
            }
            out += StudyJsonNote(
                title = title.take(200),
                body = body.take(100_000),
                topicKey = firstText(o, "topicKey", "topic")?.take(100),
                tags = parseTags(o.opt("tags")).take(2_000)
            )
        }
        if (a.length() > MAX_NOTES) warnings += "Only the first $MAX_NOTES notes were imported."
        if (skipped > 0) warnings += "$skipped invalid note${if (skipped == 1) " was" else "s were"} skipped."
        return out
    }

    private fun parseFormulas(a: JSONArray?, warnings: MutableList<String>): List<StudyJsonFormula> {
        if (a == null) return emptyList()
        val out = mutableListOf<StudyJsonFormula>()
        var skipped = 0
        for (i in 0 until minOf(a.length(), MAX_FORMULAS)) {
            val o = a.optJSONObject(i)
            val title = o?.let { firstText(it, "title", "name") }
            val expression = o?.let { firstText(it, "expression", "formula") }
            if (o == null || title == null || expression == null) {
                skipped++
                continue
            }
            out += StudyJsonFormula(
                title = title.take(200),
                expression = expression.take(10_000),
                topicKey = firstText(o, "topicKey", "topic")?.take(100),
                variables = firstText(o, "variables")?.take(10_000),
                units = firstText(o, "units")?.take(2_000),
                workedExample = firstText(o, "workedExample", "example")?.take(30_000)
            )
        }
        if (a.length() > MAX_FORMULAS) warnings += "Only the first $MAX_FORMULAS formulas were imported."
        if (skipped > 0) warnings += "$skipped invalid formula${if (skipped == 1) " was" else "s were"} skipped."
        return out
    }

    private fun parseDecks(a: JSONArray?, warnings: MutableList<String>): List<StudyJsonDeck> {
        if (a == null) return emptyList()
        val out = mutableListOf<StudyJsonDeck>()
        var total = 0
        var skipped = 0
        for (i in 0 until minOf(a.length(), MAX_DECKS)) {
            val o = a.optJSONObject(i)
            if (o == null) {
                skipped++
                continue
            }
            val name = firstText(o, "name", "title")
            val ca = o.optJSONArray("cards")
            if (name == null || ca == null) {
                skipped++
                continue
            }
            val cards = mutableListOf<StudyJsonCard>()
            for (j in 0 until ca.length()) {
                if (total >= MAX_CARDS) break
                val c = ca.optJSONObject(j) ?: continue
                val front = firstText(c, "front", "question", "prompt", "term") ?: continue
                val back = firstText(c, "back", "answer", "response", "definition") ?: continue
                val requested = firstText(c, "cardType", "type")?.uppercase()
                val type = if (requested == "CLOZE" && com.uplb.punla.data.entity.ClozeText.hasCloze(front)) {
                    FlashcardTypes.CLOZE
                } else {
                    if (requested == "CLOZE") warnings += "Card '${front.take(35)}' requested CLOZE without a {{answer}} marker; imported as Basic."
                    FlashcardTypes.BASIC
                }
                cards += StudyJsonCard(
                    front = front.take(10_000),
                    back = back.take(20_000),
                    hint = firstText(c, "hint", "clue")?.take(5_000),
                    tags = parseTags(c.opt("tags")).take(2_000),
                    starred = c.optBoolean("starred", false),
                    reverseEnabled = c.optBoolean("reverseEnabled", c.optBoolean("reverse", false)),
                    cardType = type,
                    imageUri = firstText(c, "imageUri", "image", "imageUrl")?.take(5_000),
                    occlusionJson = parseOcclusion(c.opt("occlusion"))
                )
                total++
            }
            if (cards.isNotEmpty()) {
                out += StudyJsonDeck(name.take(120), firstText(o, "description", "notes")?.take(2_000), firstText(o, "topicKey", "topic", "module")?.take(100), cards)
            } else {
                skipped++
            }
        }
        if (a.length() > MAX_DECKS) warnings += "Only the first $MAX_DECKS flashcard decks were imported."
        if (total >= MAX_CARDS) warnings += "The bundle reached the $MAX_CARDS flashcard limit; remaining cards were skipped."
        if (skipped > 0) warnings += "$skipped invalid/empty deck${if (skipped == 1) " was" else "s were"} skipped."
        return out
    }

    private fun parseQuizzes(a: JSONArray?, warnings: MutableList<String>): List<StudyJsonQuiz> {
        if(a==null)return emptyList();val out=mutableListOf<StudyJsonQuiz>();var total=0
        for(i in 0 until minOf(a.length(),MAX_QUIZZES)){val o=a.optJSONObject(i)?:continue;val title=firstText(o,"title","name")?:continue;val qa=o.optJSONArray("questions")?:continue;val questions=mutableListOf<StudyJsonQuestion>();for(j in 0 until qa.length()){if(total>=MAX_QUESTIONS)break;parseQuestion(qa.optJSONObject(j),j,warnings)?.let{questions+=it;total++}};if(questions.isNotEmpty())out+=StudyJsonQuiz(title.take(120),firstText(o,"description","notes")?.take(2_000),firstText(o,"topicKey","topic","module")?.take(100),o.optInt("passingScore",70).coerceIn(1,100),questions)}
        if(total>=MAX_QUESTIONS)warnings+="The bundle reached the $MAX_QUESTIONS quiz-question limit; remaining questions were skipped.";return out
    }

    private fun parseQuestion(o: JSONObject?, index: Int, warnings: MutableList<String>): StudyJsonQuestion? {
        o ?: return null
        val prompt = firstText(o, "question", "prompt", "stem") ?: return null
        val rawType = firstText(o, "type")?.lowercase().orEmpty()
        val type = when (rawType) {
            "true_false", "true-false", "tf" -> QuizQuestionTypes.TRUE_FALSE
            "identification", "short_answer", "typed", "text" -> QuizQuestionTypes.IDENTIFICATION
            "multi_select", "multiple_select", "select_all" -> QuizQuestionTypes.MULTI_SELECT
            "numeric", "number", "calculation" -> QuizQuestionTypes.NUMERIC
            "ordering", "order", "sequence" -> QuizQuestionTypes.ORDERING
            "matching", "match" -> QuizQuestionTypes.MATCHING
            "image", "image_identification", "diagram" -> QuizQuestionTypes.IMAGE_IDENTIFICATION
            else -> QuizQuestionTypes.MULTIPLE_CHOICE
        }
        val options = parseOptions(o.optJSONArray("choices") ?: o.optJSONArray("options") ?: o.optJSONArray("items"))
        if (type in setOf(QuizQuestionTypes.MULTIPLE_CHOICE, QuizQuestionTypes.MULTI_SELECT, QuizQuestionTypes.ORDERING) && options.size < 2) {
            warnings += "Question ${index + 1} did not have enough choices/items and was skipped."
            return null
        }
        if (type in setOf(QuizQuestionTypes.MULTIPLE_CHOICE, QuizQuestionTypes.MULTI_SELECT, QuizQuestionTypes.ORDERING) &&
            options.map(QuizQuestion::normalizeAnswer).distinct().size != options.size
        ) {
            warnings += "Question ${index + 1} had duplicate choices/items after normalization and was skipped."
            return null
        }

        val imageUri = firstText(o, "imageUri", "image", "imageUrl")?.take(5_000)
        if (type == QuizQuestionTypes.IMAGE_IDENTIFICATION && imageUri.isNullOrBlank()) {
            warnings += "Question ${index + 1} was an image question without an image and was skipped."
            return null
        }

        val raw = when {
            type == QuizQuestionTypes.MATCHING && o.optJSONObject("pairs") != null -> o.optJSONObject("pairs")
            o.has("correctAnswer") -> o.opt("correctAnswer")
            o.has("answer") -> o.opt("answer")
            o.has("correct") -> o.opt("correct")
            type == QuizQuestionTypes.ORDERING -> JSONArray(options)
            else -> null
        } ?: return null

        val answer = when (type) {
            QuizQuestionTypes.MULTIPLE_CHOICE -> {
                when (raw) {
                    is Number -> options.getOrNull(raw.toInt())
                    is Boolean -> if (raw) "True" else "False"
                    else -> {
                        val text = raw.toString().trim()
                        if (text.length == 1 && text[0].uppercaseChar() in 'A'..'H') {
                            options.getOrNull(text[0].uppercaseChar() - 'A')
                        } else text
                    }
                }?.takeIf { candidate ->
                    options.any { QuizQuestion.normalizeAnswer(it) == QuizQuestion.normalizeAnswer(candidate) }
                } ?: return null
            }
            QuizQuestionTypes.TRUE_FALSE -> when (raw) {
                is Boolean -> if (raw) "True" else "False"
                else -> raw.toString().trim().let {
                    when {
                        it.equals("true", true) -> "True"
                        it.equals("false", true) -> "False"
                        else -> return null
                    }
                }
            }
            QuizQuestionTypes.MULTI_SELECT -> {
                val chosen = when (raw) {
                    is JSONArray -> List(raw.length()) { raw.optString(it).trim() }.filter { it.isNotEmpty() }
                    else -> raw.toString().split('|', ',').map { it.trim() }.filter { it.isNotEmpty() }
                }
                val resolved = chosen.mapNotNull { token ->
                    if (token.length == 1 && token[0].uppercaseChar() in 'A'..'H') {
                        options.getOrNull(token[0].uppercaseChar() - 'A')
                    } else {
                        options.firstOrNull { QuizQuestion.normalizeAnswer(it) == QuizQuestion.normalizeAnswer(token) }
                    }
                }.distinct()
                if (resolved.isEmpty() || resolved.size != chosen.distinctBy { it.lowercase() }.size) return null
                JSONArray(resolved).toString()
            }
            QuizQuestionTypes.ORDERING -> {
                val tokens = when (raw) {
                    is JSONArray -> List(raw.length()) { raw.optString(it).trim() }.filter { it.isNotEmpty() }
                    else -> raw.toString().split('|').map { it.trim() }.filter { it.isNotEmpty() }
                }
                val resolved = tokens.mapNotNull { token ->
                    if (token.length == 1 && token[0].uppercaseChar() in 'A'..'H') {
                        options.getOrNull(token[0].uppercaseChar() - 'A')
                    } else {
                        options.firstOrNull { QuizQuestion.normalizeAnswer(it) == QuizQuestion.normalizeAnswer(token) }
                    }
                }
                val normalizedOptions = options.map { QuizQuestion.normalizeAnswer(it) }
                val normalizedResolved = resolved.map { QuizQuestion.normalizeAnswer(it) }
                if (tokens.size != options.size || resolved.size != tokens.size || normalizedResolved.toSet() != normalizedOptions.toSet()) return null
                JSONArray(resolved).toString()
            }
            QuizQuestionTypes.MATCHING -> {
                val pairs = when (raw) {
                    is JSONObject -> raw
                    else -> runCatching { JSONObject(raw.toString()) }.getOrNull()
                } ?: return null
                val clean = JSONObject()
                pairs.keys().forEach { key ->
                    val left = key.trim()
                    val right = pairs.optString(key).trim()
                    if (left.isNotEmpty() && right.isNotEmpty()) clean.put(left, right)
                }
                if (clean.length() < 2) return null
                clean.toString()
            }
            QuizQuestionTypes.NUMERIC -> raw.toString().trim().takeIf { it.toDoubleOrNull() != null } ?: return null
            else -> raw.toString().trim().takeIf { it.isNotEmpty() } ?: return null
        }

        val metadata = JSONObject().apply {
            if (o.has("tolerance")) put("tolerance", o.optDouble("tolerance", 0.0).coerceAtLeast(0.0))
            o.optJSONObject("metadata")?.let { m -> m.keys().forEach { key -> put(key, m.opt(key)) } }
        }.toString()

        return StudyJsonQuestion(
            type = type,
            prompt = prompt.take(20_000),
            options = options.take(30),
            correctAnswer = answer.take(30_000),
            explanation = firstText(o, "explanation", "feedback", "rationale")?.take(30_000),
            tags = parseTags(o.opt("tags")).take(1_000),
            metadataJson = metadata,
            imageUri = imageUri
        )
    }

    private fun parseOptions(a: JSONArray?): List<String> {
        if (a == null) return emptyList()
        return buildList {
            for (i in 0 until minOf(a.length(), 30)) {
                a.optString(i).trim().takeIf { it.isNotEmpty() }?.let(::add)
            }
        }
        // Duplicate choices stay visible to parseQuestion, which rejects them
        // before any letter/index answer can be remapped.
    }
    private fun parseOcclusion(value: Any?): String = when (value) {
        is JSONArray -> value.toString()
        is JSONObject -> JSONArray().put(value).toString()
        is String -> runCatching { JSONArray(value).toString() }.getOrDefault("[]")
        else -> "[]"
    }

    private fun parseTags(value:Any?):String=when(value){is JSONArray->buildList{for(i in 0 until value.length())value.optString(i).trim().takeIf{it.isNotEmpty()}?.let(::add)}.distinct().joinToString(", ");is String->value.split(',').map{it.trim()}.filter{it.isNotEmpty()}.distinct().joinToString(", ");else->""}
    private fun firstText(obj:JSONObject?,vararg keys:String):String?{if(obj==null)return null;for(key in keys){if(!obj.has(key)||obj.isNull(key))continue;val v=obj.optString(key).trim();if(v.isNotEmpty())return v};return null}
}
